### ISSUE TITLE
Update WiFi obtainment method

### ISSUE THREAD

**Issue by bogeholm** [bogeholm/pidns#11]
```bash
ubuntu@ubuntu$ cat /etc/netplan/50-cloud-init.yaml 
```

```yaml
...
network:
    ethernets:
        eth0:
            dhcp4: true
            optional: true
    version: 2
    wifis:
        wlan0:
            optional: true
            access-points:
                "{{WiFi SSID}}":
                    password: "{{WiFi Passphrase}}"
            dhcp4: true
```
